# Generated by Django 2.0.3 on 2018-11-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_data',
            new_name='ProductData',
        ),
    ]
